# coding: utf-8

"""
    OANDA v20 REST API

    The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.

    The version of the OpenAPI document: 3.0.25
    Contact: api@oanda.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import pyfx.dispatch.oanda
from pyfx.dispatch.oanda.models.list_transactions200_response import ListTransactions200Response  # noqa: E501
from pyfx.dispatch.oanda.rest import ApiException

class TestListTransactions200Response(unittest.TestCase):
    """ListTransactions200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ListTransactions200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListTransactions200Response`
        """
        model = pyfx.dispatch.oanda.models.list_transactions200_response.ListTransactions200Response()  # noqa: E501
        if include_optional :
            return ListTransactions200Response(
                var_from = '', 
                to = '', 
                page_size = 56, 
                type = [
                    'ORDER'
                    ], 
                count = 56, 
                pages = [
                    ''
                    ], 
                last_transaction_id = ''
            )
        else :
            return ListTransactions200Response(
        )
        """

    def testListTransactions200Response(self):
        """Test ListTransactions200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
