# coding: utf-8

"""
    OANDA v20 REST API

    The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.

    The version of the OpenAPI document: 3.0.25
    Contact: api@oanda.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import pyfx.dispatch.oanda
from pyfx.dispatch.oanda.models.get_transaction200_response import GetTransaction200Response  # noqa: E501
from pyfx.dispatch.oanda.rest import ApiException

class TestGetTransaction200Response(unittest.TestCase):
    """GetTransaction200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GetTransaction200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetTransaction200Response`
        """
        model = pyfx.dispatch.oanda.models.get_transaction200_response.GetTransaction200Response()  # noqa: E501
        if include_optional :
            return GetTransaction200Response(
                transaction = pyfx.dispatch.oanda.models.transaction.Transaction(
                    id = '', 
                    time = '', 
                    user_id = 56, 
                    account_id = '', 
                    batch_id = '', 
                    request_id = '', ), 
                last_transaction_id = ''
            )
        else :
            return GetTransaction200Response(
        )
        """

    def testGetTransaction200Response(self):
        """Test GetTransaction200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
