# coding: utf-8

"""
    OANDA v20 REST API

    The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.

    The version of the OpenAPI document: 3.0.25

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import pyfx.dispatch.oanda
from pyfx.dispatch.oanda.models.get_external_user_info200_response import GetExternalUserInfo200Response  # noqa: E501
from pyfx.dispatch.oanda.rest import ApiException

class TestGetExternalUserInfo200Response(unittest.TestCase):
    """GetExternalUserInfo200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GetExternalUserInfo200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetExternalUserInfo200Response`
        """
        model = pyfx.dispatch.oanda.models.get_external_user_info200_response.GetExternalUserInfo200Response()  # noqa: E501
        if include_optional :
            return GetExternalUserInfo200Response(
                user_info = pyfx.dispatch.oanda.models.user_info_external.UserInfoExternal(
                    user_id = 56, 
                    country = '', 
                    fifo = True, )
            )
        else :
            return GetExternalUserInfo200Response(
        )
        """

    def testGetExternalUserInfo200Response(self):
        """Test GetExternalUserInfo200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
