# coding: utf-8

"""
    OANDA v20 REST API

    The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.

    The version of the OpenAPI document: 3.0.25
    Contact: api@oanda.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import pyfx.dispatch.oanda
from pyfx.dispatch.oanda.models.order_fill_reason import OrderFillReason  # noqa: E501
from pyfx.dispatch.oanda.rest import ApiException

class TestOrderFillReason(unittest.TestCase):
    """OrderFillReason unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderFillReason(self):
        """Test OrderFillReason"""
        # inst = OrderFillReason()

if __name__ == '__main__':
    unittest.main()
