# coding: utf-8

"""
    OANDA v20 REST API

    The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.

    The version of the OpenAPI document: 3.0.25

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import pyfx.dispatch.oanda
from pyfx.dispatch.oanda.models.time_in_force import TimeInForce  # noqa: E501
from pyfx.dispatch.oanda.rest import ApiException

class TestTimeInForce(unittest.TestCase):
    """TimeInForce unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTimeInForce(self):
        """Test TimeInForce"""
        # inst = TimeInForce()

if __name__ == '__main__':
    unittest.main()
