# coding: utf-8

"""
    OANDA v20 REST API

    The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.

    The version of the OpenAPI document: 3.0.25

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import pyfx.dispatch.oanda
from pyfx.dispatch.oanda.models.trade_summary import TradeSummary  # noqa: E501
from pyfx.dispatch.oanda.rest import ApiException

class TestTradeSummary(unittest.TestCase):
    """TradeSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TradeSummary
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TradeSummary`
        """
        model = pyfx.dispatch.oanda.models.trade_summary.TradeSummary()  # noqa: E501
        if include_optional :
            return TradeSummary(
                id = '', 
                instrument = '', 
                price = '', 
                open_time = '', 
                state = 'OPEN', 
                initial_units = '', 
                initial_margin_required = '', 
                current_units = '', 
                realized_pl = '', 
                unrealized_pl = '', 
                margin_used = '', 
                average_close_price = '', 
                closing_transaction_ids = [
                    ''
                    ], 
                financing = '', 
                close_time = '', 
                client_extensions = pyfx.dispatch.oanda.models.client_extensions.ClientExtensions(
                    id = '', 
                    tag = '', 
                    comment = '', ), 
                take_profit_order_id = '', 
                stop_loss_order_id = '', 
                trailing_stop_loss_order_id = ''
            )
        else :
            return TradeSummary(
        )
        """

    def testTradeSummary(self):
        """Test TradeSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
