# coding: utf-8

"""
    OANDA v20 REST API

    The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.

    The version of the OpenAPI document: 3.0.25
    Contact: api@oanda.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import pyfx.dispatch.oanda
from pyfx.dispatch.oanda.models.account_summary import AccountSummary  # noqa: E501
from pyfx.dispatch.oanda.rest import ApiException

class TestAccountSummary(unittest.TestCase):
    """AccountSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AccountSummary
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountSummary`
        """
        model = pyfx.dispatch.oanda.models.account_summary.AccountSummary()  # noqa: E501
        if include_optional :
            return AccountSummary(
                id = '', 
                alias = '', 
                currency = '', 
                balance = '', 
                created_by_user_id = 56, 
                created_time = '', 
                guaranteed_stop_loss_order_mode = 'DISABLED', 
                pl = '', 
                resettable_pl = '', 
                resettable_pl_time = '', 
                financing = '', 
                commission = '', 
                guaranteed_execution_fees = '', 
                margin_rate = '', 
                margin_call_enter_time = '', 
                margin_call_extension_count = 56, 
                last_margin_call_extension_time = '', 
                open_trade_count = 56, 
                open_position_count = 56, 
                pending_order_count = 56, 
                hedging_enabled = True, 
                last_order_fill_timestamp = '', 
                unrealized_pl = '', 
                nav = '', 
                margin_used = '', 
                margin_available = '', 
                position_value = '', 
                margin_closeout_unrealized_pl = '', 
                margin_closeout_nav = '', 
                margin_closeout_margin_used = '', 
                margin_closeout_percent = '', 
                margin_closeout_position_value = '', 
                withdrawal_limit = '', 
                margin_call_margin_used = '', 
                margin_call_percent = '', 
                last_transaction_id = ''
            )
        else :
            return AccountSummary(
        )
        """

    def testAccountSummary(self):
        """Test AccountSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
