# coding: utf-8

"""
    OANDA v20 REST API

    The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.

    The version of the OpenAPI document: 3.0.25
    Contact: api@oanda.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import pyfx.dispatch.oanda
from pyfx.dispatch.oanda.models.get_account_changes200_response import GetAccountChanges200Response  # noqa: E501
from pyfx.dispatch.oanda.rest import ApiException

class TestGetAccountChanges200Response(unittest.TestCase):
    """GetAccountChanges200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GetAccountChanges200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAccountChanges200Response`
        """
        model = pyfx.dispatch.oanda.models.get_account_changes200_response.GetAccountChanges200Response()  # noqa: E501
        if include_optional :
            return GetAccountChanges200Response(
                changes = pyfx.dispatch.oanda.models.account_changes.AccountChanges(
                    orders_created = [
                        pyfx.dispatch.oanda.models.order.Order(
                            id = '', 
                            create_time = '', 
                            state = 'PENDING', 
                            client_extensions = pyfx.dispatch.oanda.models.client_extensions.ClientExtensions(
                                id = '', 
                                tag = '', 
                                comment = '', ), )
                        ], 
                    orders_cancelled = [
                        pyfx.dispatch.oanda.models.order.Order(
                            id = '', 
                            create_time = '', 
                            state = 'PENDING', )
                        ], 
                    orders_filled = [
                        
                        ], 
                    orders_triggered = [
                        
                        ], 
                    trades_opened = [
                        pyfx.dispatch.oanda.models.trade_summary.TradeSummary(
                            id = '', 
                            instrument = '', 
                            price = '', 
                            open_time = '', 
                            state = 'OPEN', 
                            initial_units = '', 
                            initial_margin_required = '', 
                            current_units = '', 
                            realized_pl = '', 
                            unrealized_pl = '', 
                            margin_used = '', 
                            average_close_price = '', 
                            closing_transaction_ids = [
                                ''
                                ], 
                            financing = '', 
                            close_time = '', 
                            take_profit_order_id = '', 
                            stop_loss_order_id = '', 
                            trailing_stop_loss_order_id = '', )
                        ], 
                    trades_reduced = [
                        pyfx.dispatch.oanda.models.trade_summary.TradeSummary(
                            id = '', 
                            instrument = '', 
                            price = '', 
                            open_time = '', 
                            state = 'OPEN', 
                            initial_units = '', 
                            initial_margin_required = '', 
                            current_units = '', 
                            realized_pl = '', 
                            unrealized_pl = '', 
                            margin_used = '', 
                            average_close_price = '', 
                            financing = '', 
                            close_time = '', 
                            take_profit_order_id = '', 
                            stop_loss_order_id = '', 
                            trailing_stop_loss_order_id = '', )
                        ], 
                    trades_closed = [
                        
                        ], 
                    positions = [
                        pyfx.dispatch.oanda.models.position.Position(
                            instrument = '', 
                            pl = '', 
                            unrealized_pl = '', 
                            margin_used = '', 
                            resettable_pl = '', 
                            financing = '', 
                            commission = '', 
                            guaranteed_execution_fees = '', 
                            long = pyfx.dispatch.oanda.models.position_side.PositionSide(
                                units = '', 
                                average_price = '', 
                                trade_ids = [
                                    ''
                                    ], 
                                pl = '', 
                                unrealized_pl = '', 
                                resettable_pl = '', 
                                financing = '', 
                                guaranteed_execution_fees = '', ), 
                            short = pyfx.dispatch.oanda.models.position_side.PositionSide(
                                units = '', 
                                average_price = '', 
                                pl = '', 
                                unrealized_pl = '', 
                                resettable_pl = '', 
                                financing = '', 
                                guaranteed_execution_fees = '', ), )
                        ], 
                    transactions = [
                        pyfx.dispatch.oanda.models.transaction.Transaction(
                            id = '', 
                            time = '', 
                            user_id = 56, 
                            account_id = '', 
                            batch_id = '', 
                            request_id = '', )
                        ], ), 
                state = pyfx.dispatch.oanda.models.account_changes_state.AccountChangesState(
                    unrealized_pl = '', 
                    nav = '', 
                    margin_used = '', 
                    margin_available = '', 
                    position_value = '', 
                    margin_closeout_unrealized_pl = '', 
                    margin_closeout_nav = '', 
                    margin_closeout_margin_used = '', 
                    margin_closeout_percent = '', 
                    margin_closeout_position_value = '', 
                    withdrawal_limit = '', 
                    margin_call_margin_used = '', 
                    margin_call_percent = '', 
                    orders = [
                        pyfx.dispatch.oanda.models.dynamic_order_state.DynamicOrderState(
                            id = '', 
                            trailing_stop_value = '', 
                            trigger_distance = '', 
                            is_trigger_distance_exact = True, )
                        ], 
                    trades = [
                        pyfx.dispatch.oanda.models.calculated_trade_state.CalculatedTradeState(
                            id = '', 
                            unrealized_pl = '', 
                            margin_used = '', )
                        ], 
                    positions = [
                        pyfx.dispatch.oanda.models.calculated_position_state.CalculatedPositionState(
                            instrument = '', 
                            net_unrealized_pl = '', 
                            long_unrealized_pl = '', 
                            short_unrealized_pl = '', 
                            margin_used = '', )
                        ], ), 
                last_transaction_id = ''
            )
        else :
            return GetAccountChanges200Response(
        )
        """

    def testGetAccountChanges200Response(self):
        """Test GetAccountChanges200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
