# coding: utf-8

"""
    OANDA v20 REST API

    The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.

    The version of the OpenAPI document: 3.0.25
    Contact: api@oanda.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import pyfx.dispatch.oanda
from pyfx.dispatch.oanda.models.market_order_reason import MarketOrderReason  # noqa: E501
from pyfx.dispatch.oanda.rest import ApiException

class TestMarketOrderReason(unittest.TestCase):
    """MarketOrderReason unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMarketOrderReason(self):
        """Test MarketOrderReason"""
        # inst = MarketOrderReason()

if __name__ == '__main__':
    unittest.main()
