# coding: utf-8

"""
    OANDA v20 REST API

    The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.

    The version of the OpenAPI document: 3.0.25
    Contact: api@oanda.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import pyfx.dispatch.oanda
from pyfx.dispatch.oanda.models.account_changes_state import AccountChangesState  # noqa: E501
from pyfx.dispatch.oanda.rest import ApiException

class TestAccountChangesState(unittest.TestCase):
    """AccountChangesState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AccountChangesState
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountChangesState`
        """
        model = pyfx.dispatch.oanda.models.account_changes_state.AccountChangesState()  # noqa: E501
        if include_optional :
            return AccountChangesState(
                unrealized_pl = '', 
                nav = '', 
                margin_used = '', 
                margin_available = '', 
                position_value = '', 
                margin_closeout_unrealized_pl = '', 
                margin_closeout_nav = '', 
                margin_closeout_margin_used = '', 
                margin_closeout_percent = '', 
                margin_closeout_position_value = '', 
                withdrawal_limit = '', 
                margin_call_margin_used = '', 
                margin_call_percent = '', 
                orders = [
                    pyfx.dispatch.oanda.models.dynamic_order_state.DynamicOrderState(
                        id = '', 
                        trailing_stop_value = '', 
                        trigger_distance = '', 
                        is_trigger_distance_exact = True, )
                    ], 
                trades = [
                    pyfx.dispatch.oanda.models.calculated_trade_state.CalculatedTradeState(
                        id = '', 
                        unrealized_pl = '', 
                        margin_used = '', )
                    ], 
                positions = [
                    pyfx.dispatch.oanda.models.calculated_position_state.CalculatedPositionState(
                        instrument = '', 
                        net_unrealized_pl = '', 
                        long_unrealized_pl = '', 
                        short_unrealized_pl = '', 
                        margin_used = '', )
                    ]
            )
        else :
            return AccountChangesState(
        )
        """

    def testAccountChangesState(self):
        """Test AccountChangesState"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
