# coding: utf-8

"""
    OANDA v20 REST API

    The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.

    The version of the OpenAPI document: 3.0.25
    Contact: api@oanda.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import pyfx.dispatch.oanda
from pyfx.dispatch.oanda.models.client_price import ClientPrice  # noqa: E501
from pyfx.dispatch.oanda.rest import ApiException

class TestClientPrice(unittest.TestCase):
    """ClientPrice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ClientPrice
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClientPrice`
        """
        model = pyfx.dispatch.oanda.models.client_price.ClientPrice()  # noqa: E501
        if include_optional :
            return ClientPrice(
                type = '', 
                instrument = '', 
                time = '', 
                status = 'tradeable', 
                tradeable = True, 
                bids = [
                    pyfx.dispatch.oanda.models.price_bucket.PriceBucket(
                        price = '', 
                        liquidity = 56, )
                    ], 
                asks = [
                    pyfx.dispatch.oanda.models.price_bucket.PriceBucket(
                        price = '', 
                        liquidity = 56, )
                    ], 
                closeout_bid = '', 
                closeout_ask = '', 
                quote_home_conversion_factors = pyfx.dispatch.oanda.models.quote_home_conversion_factors.QuoteHomeConversionFactors(
                    positive_units = '', 
                    negative_units = '', ), 
                units_available = pyfx.dispatch.oanda.models.units_available.UnitsAvailable(
                    default = pyfx.dispatch.oanda.models.units_available_details.UnitsAvailableDetails(
                        long = '', 
                        short = '', ), 
                    reduce_first = pyfx.dispatch.oanda.models.units_available_details.UnitsAvailableDetails(
                        long = '', 
                        short = '', ), 
                    reduce_only = , 
                    open_only = , )
            )
        else :
            return ClientPrice(
        )
        """

    def testClientPrice(self):
        """Test ClientPrice"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
