# coding: utf-8

"""
    OANDA v20 REST API

    The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.

    The version of the OpenAPI document: 3.0.25

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import pyfx.dispatch.oanda
from pyfx.dispatch.oanda.models.account_financing_mode import AccountFinancingMode  # noqa: E501
from pyfx.dispatch.oanda.rest import ApiException

class TestAccountFinancingMode(unittest.TestCase):
    """AccountFinancingMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountFinancingMode(self):
        """Test AccountFinancingMode"""
        # inst = AccountFinancingMode()

if __name__ == '__main__':
    unittest.main()
