# coding: utf-8

"""
    OANDA v20 REST API

    The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.

    The version of the OpenAPI document: 3.0.25
    Contact: api@oanda.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import pyfx.dispatch.oanda
from pyfx.dispatch.oanda.models.instrument import Instrument  # noqa: E501
from pyfx.dispatch.oanda.rest import ApiException

class TestInstrument(unittest.TestCase):
    """Instrument unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Instrument
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Instrument`
        """
        model = pyfx.dispatch.oanda.models.instrument.Instrument()  # noqa: E501
        if include_optional :
            return Instrument(
                name = '', 
                type = 'CURRENCY', 
                display_name = '', 
                pip_location = 56, 
                display_precision = 56, 
                trade_units_precision = 56, 
                minimum_trade_size = '', 
                maximum_trailing_stop_distance = '', 
                minimum_trailing_stop_distance = '', 
                maximum_position_size = '', 
                maximum_order_units = '', 
                margin_rate = '', 
                commission = pyfx.dispatch.oanda.models.instrument_commission.InstrumentCommission(
                    commission = '', 
                    units_traded = '', 
                    minimum_commission = '', )
            )
        else :
            return Instrument(
        )
        """

    def testInstrument(self):
        """Test Instrument"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
