# coding: utf-8

"""
    OANDA v20 REST API

    The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.

    The version of the OpenAPI document: 3.0.25
    Contact: api@oanda.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import pyfx.dispatch.oanda
from pyfx.dispatch.oanda.models.order_type import OrderType  # noqa: E501
from pyfx.dispatch.oanda.rest import ApiException

class TestOrderType(unittest.TestCase):
    """OrderType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderType(self):
        """Test OrderType"""
        # inst = OrderType()

if __name__ == '__main__':
    unittest.main()
