[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.urls]
Home = "https://github.com/fxtatools/pyfx_dispatch_oanda"

[project]
name = "pyfx.dispatch.oanda"
version = "1.0.0"
description = "aio support for OANDA v20 REST API (Unofficial)"
authors = [{ name = "Sean Champ", email = "spchamp@users.noreply.github.com" }]
license = { file = "COPYING" }
readme = "README.md"
keywords = ["OpenAPI", "OpenAPI-Generator", "OANDA v20 REST API"]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Private :: Do not Upload",
]
dependencies = [
    "urllib3 >= 1.25.3",
    "python-dateutil >=2.8.2",
    "aiohttp >= 3.8.4",
    "pydantic >1.10.5, <2",
    "aenum >=3.1.11",
]
requires-python = "> 3.7"

[project.optional-dependencies]
dev = [
    "pytest >=7.2.1",
    "pytest-cov>=2.8.1",
    "pytest-randomly>=3.12.0",
    "tox >=3.9.0",
    "flake8 >=4.0.0",
    "autopep8",
    "pip-tools",
]

[tool.setuptools.packages.find]
where = ["src"]
namespaces = true

[tool.pytest.ini_options]
testpaths = ["test"]

[tool.pylint.'MESSAGES CONTROL']
extension-pkg-whitelist = "pydantic"
