# coding: utf-8

"""
    OANDA v20 REST API

    The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.

    The version of the OpenAPI document: 3.0.25

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, Optional
from pydantic import BaseModel, Field, StrictStr
from pyfx.dispatch.oanda.models.client_configure_reject_transaction import ClientConfigureRejectTransaction

class ConfigureAccount400Response(BaseModel):
    """
    ConfigureAccount400Response
    """
    client_configure_reject_transaction: Optional[ClientConfigureRejectTransaction] = Field(None, alias="clientConfigureRejectTransaction")
    last_transaction_id: Optional[StrictStr] = Field(None, alias="lastTransactionID", description="The ID of the last Transaction created for the Account.")
    error_code: Optional[StrictStr] = Field(None, alias="errorCode", description="The code of the error that has occurred. This field may not be returned for some errors.")
    error_message: Optional[StrictStr] = Field(None, alias="errorMessage", description="The human-readable description of the error that has occurred.")
    additional_properties: Dict[str, Any] = {}
    __properties = ["clientConfigureRejectTransaction", "lastTransactionID", "errorCode", "errorMessage"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> "ConfigureAccount400Response":
        """Create an instance of ConfigureAccount400Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "additional_properties"
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of client_configure_reject_transaction
        if self.client_configure_reject_transaction:
            _dict['clientConfigureRejectTransaction'] = self.client_configure_reject_transaction.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ConfigureAccount400Response:
        """Create an instance of ConfigureAccount400Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ConfigureAccount400Response.parse_obj(obj)

        _obj = ConfigureAccount400Response.parse_obj({
            "client_configure_reject_transaction": ClientConfigureRejectTransaction.from_dict(obj.get("clientConfigureRejectTransaction")) if obj.get("clientConfigureRejectTransaction") is not None else None,
            "last_transaction_id": obj.get("lastTransactionID"),
            "error_code": obj.get("errorCode"),
            "error_message": obj.get("errorMessage")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


