# coding: utf-8

"""
    OANDA v20 REST API

    The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.

    The version of the OpenAPI document: 3.0.25

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist, validator
from pyfx.dispatch.oanda.models.candlestick import Candlestick

class GetInstrumentCandles200Response(BaseModel):
    """
    GetInstrumentCandles200Response
    """
    instrument: Optional[StrictStr] = Field(None, description="The instrument whose Prices are represented by the candlesticks.")
    granularity: Optional[StrictStr] = Field(None, description="The granularity of the candlesticks provided.")
    candles: Optional[conlist(Candlestick)] = Field(None, description="The list of candlesticks that satisfy the request.")
    additional_properties: Dict[str, Any] = {}
    __properties = ["instrument", "granularity", "candles"]

    @validator('granularity')
    def granularity_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('S5', 'S10', 'S15', 'S30', 'M1', 'M2', 'M4', 'M5', 'M10', 'M15', 'M30', 'H1', 'H2', 'H3', 'H4', 'H6', 'H8', 'H12', 'D', 'W', 'M'):
            raise ValueError("must be one of enum values ('S5', 'S10', 'S15', 'S30', 'M1', 'M2', 'M4', 'M5', 'M10', 'M15', 'M30', 'H1', 'H2', 'H3', 'H4', 'H6', 'H8', 'H12', 'D', 'W', 'M')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = __debug__

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> "GetInstrumentCandles200Response":
        """Create an instance of GetInstrumentCandles200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "additional_properties"
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in candles (list)
        _items = []
        if self.candles:
            for _item in self.candles:
                if _item:
                    _items.append(_item.to_dict())
            _dict['candles'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GetInstrumentCandles200Response:
        """Create an instance of GetInstrumentCandles200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return GetInstrumentCandles200Response.parse_obj(obj)

        _obj = GetInstrumentCandles200Response.parse_obj({
            "instrument": obj.get("instrument"),
            "granularity": obj.get("granularity"),
            "candles": [Candlestick.from_dict(_item) for _item in obj.get("candles")] if obj.get("candles") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


