# coding: utf-8

"""
    OANDA v20 REST API

    The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.

    The version of the OpenAPI document: 3.0.25

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, Optional
from pydantic import BaseModel, Field, StrictStr

class PositionBookBucket(BaseModel):
    """
    The position book data for a partition of the instrument's prices.
    """
    price: Optional[StrictStr] = Field(None, description="The lowest price (inclusive) covered by the bucket. The bucket covers the price range from the price to price + the position book's bucketWidth.")
    long_count_percent: Optional[StrictStr] = Field(None, alias="longCountPercent", description="The percentage of the total number of positions represented by the long positions found in this bucket.")
    short_count_percent: Optional[StrictStr] = Field(None, alias="shortCountPercent", description="The percentage of the total number of positions represented by the short positions found in this bucket.")
    additional_properties: Dict[str, Any] = {}
    __properties = ["price", "longCountPercent", "shortCountPercent"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = __debug__

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> "PositionBookBucket":
        """Create an instance of PositionBookBucket from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "additional_properties"
                          },
                          exclude_none=True)
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PositionBookBucket:
        """Create an instance of PositionBookBucket from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PositionBookBucket.parse_obj(obj)

        _obj = PositionBookBucket.parse_obj({
            "price": obj.get("price"),
            "long_count_percent": obj.get("longCountPercent"),
            "short_count_percent": obj.get("shortCountPercent")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


