# coding: utf-8

"""
    OANDA v20 REST API

    The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.

    The version of the OpenAPI document: 3.0.25

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist
from pyfx.dispatch.oanda.models.open_trade_financing import OpenTradeFinancing

class PositionFinancing(BaseModel):
    """
    OpenTradeFinancing is used to pay/collect daily financing charge for a Position within an Account
    """
    instrument: Optional[StrictStr] = Field(None, description="The instrument of the Position that financing is being paid/collected for.")
    financing: Optional[StrictStr] = Field(None, description="The amount of financing paid/collected for the Position.")
    open_trade_financings: Optional[conlist(OpenTradeFinancing)] = Field(None, alias="openTradeFinancings", description="The financing paid/collecte for each open Trade within the Position.")
    additional_properties: Dict[str, Any] = {}
    __properties = ["instrument", "financing", "openTradeFinancings"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> "PositionFinancing":
        """Create an instance of PositionFinancing from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "additional_properties"
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in open_trade_financings (list)
        _items = []
        if self.open_trade_financings:
            for _item in self.open_trade_financings:
                if _item:
                    _items.append(_item.to_dict())
            _dict['openTradeFinancings'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PositionFinancing:
        """Create an instance of PositionFinancing from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PositionFinancing.parse_obj(obj)

        _obj = PositionFinancing.parse_obj({
            "instrument": obj.get("instrument"),
            "financing": obj.get("financing"),
            "open_trade_financings": [OpenTradeFinancing.from_dict(_item) for _item in obj.get("openTradeFinancings")] if obj.get("openTradeFinancings") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


