# coding: utf-8

"""
    OANDA v20 REST API

    The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.

    The version of the OpenAPI document: 3.0.25

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class PriceStatus(str, Enum):
    """
    The status of the Price.
    """

    """
    allowed enum values
    """
    TRADEABLE = 'tradeable'
    NON_MINUS_TRADEABLE = 'non-tradeable'
    INVALID = 'invalid'

    @classmethod
    def from_json(cls, json_str: str) -> "PriceStatus":
        """Create an instance of PriceStatus from a JSON string"""
        return PriceStatus(json.loads(json_str))


