# coding: utf-8

"""
    OANDA v20 REST API

    The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.

    The version of the OpenAPI document: 3.0.25

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class TakeProfitOrderReason(str, Enum):
    """
    The reason that the Take Profit Order was initiated
    """

    """
    allowed enum values
    """
    CLIENT_ORDER = 'CLIENT_ORDER'
    REPLACEMENT = 'REPLACEMENT'
    ON_FILL = 'ON_FILL'

    @classmethod
    def from_json(cls, json_str: str) -> "TakeProfitOrderReason":
        """Create an instance of TakeProfitOrderReason from a JSON string"""
        return TakeProfitOrderReason(json.loads(json_str))


