# coding: utf-8

"""
    OANDA v20 REST API

    The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.

    The version of the OpenAPI document: 3.0.25

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, Optional
from pydantic import BaseModel, Field, StrictStr, validator
from pyfx.dispatch.oanda.models.client_extensions import ClientExtensions

class TakeProfitDetails(BaseModel):
    """
    TakeProfitDetails specifies the details of a Take Profit Order to be created on behalf of a client. This may happen when an Order is filled that opens a Trade requiring a Take Profit, or when a Trade's dependent Take Profit Order is modified directly through the Trade.
    """
    price: Optional[StrictStr] = Field(None, description="The price that the Take Profit Order will be triggered at. Only one of the price and distance fields may be specified.")
    time_in_force: Optional[StrictStr] = Field(None, alias="timeInForce", description="The time in force for the created Take Profit Order. This may only be GTC, GTD or GFD.")
    gtd_time: Optional[StrictStr] = Field(None, alias="gtdTime", description="The date when the Take Profit Order will be cancelled on if timeInForce is GTD.")
    client_extensions: Optional[ClientExtensions] = Field(None, alias="clientExtensions")
    additional_properties: Dict[str, Any] = {}
    __properties = ["price", "timeInForce", "gtdTime", "clientExtensions"]

    @validator('time_in_force')
    def time_in_force_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('GTC', 'GTD', 'GFD', 'FOK', 'IOC'):
            raise ValueError("must be one of enum values ('GTC', 'GTD', 'GFD', 'FOK', 'IOC')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> "TakeProfitDetails":
        """Create an instance of TakeProfitDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "additional_properties"
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of client_extensions
        if self.client_extensions:
            _dict['clientExtensions'] = self.client_extensions.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TakeProfitDetails:
        """Create an instance of TakeProfitDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TakeProfitDetails.parse_obj(obj)

        _obj = TakeProfitDetails.parse_obj({
            "price": obj.get("price"),
            "time_in_force": obj.get("timeInForce"),
            "gtd_time": obj.get("gtdTime"),
            "client_extensions": ClientExtensions.from_dict(obj.get("clientExtensions")) if obj.get("clientExtensions") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


