# coding: utf-8

"""
    OANDA v20 REST API

    The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.

    The version of the OpenAPI document: 3.0.25

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist
from pyfx.dispatch.oanda.models.market_order_transaction import MarketOrderTransaction
from pyfx.dispatch.oanda.models.order_cancel_transaction import OrderCancelTransaction
from pyfx.dispatch.oanda.models.order_fill_transaction import OrderFillTransaction

class ClosePosition200Response(BaseModel):
    """
    ClosePosition200Response
    """
    long_order_create_transaction: Optional[MarketOrderTransaction] = Field(None, alias="longOrderCreateTransaction")
    long_order_fill_transaction: Optional[OrderFillTransaction] = Field(None, alias="longOrderFillTransaction")
    long_order_cancel_transaction: Optional[OrderCancelTransaction] = Field(None, alias="longOrderCancelTransaction")
    short_order_create_transaction: Optional[MarketOrderTransaction] = Field(None, alias="shortOrderCreateTransaction")
    short_order_fill_transaction: Optional[OrderFillTransaction] = Field(None, alias="shortOrderFillTransaction")
    short_order_cancel_transaction: Optional[OrderCancelTransaction] = Field(None, alias="shortOrderCancelTransaction")
    related_transaction_ids: Optional[conlist(StrictStr)] = Field(None, alias="relatedTransactionIDs", description="The IDs of all Transactions that were created while satisfying the request.")
    last_transaction_id: Optional[StrictStr] = Field(None, alias="lastTransactionID", description="The ID of the most recent Transaction created for the Account")
    additional_properties: Dict[str, Any] = {}
    __properties = ["longOrderCreateTransaction", "longOrderFillTransaction", "longOrderCancelTransaction", "shortOrderCreateTransaction", "shortOrderFillTransaction", "shortOrderCancelTransaction", "relatedTransactionIDs", "lastTransactionID"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ClosePosition200Response:
        """Create an instance of ClosePosition200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "additional_properties"
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of long_order_create_transaction
        if self.long_order_create_transaction:
            _dict['longOrderCreateTransaction'] = self.long_order_create_transaction.to_dict()
        # override the default output from pydantic by calling `to_dict()` of long_order_fill_transaction
        if self.long_order_fill_transaction:
            _dict['longOrderFillTransaction'] = self.long_order_fill_transaction.to_dict()
        # override the default output from pydantic by calling `to_dict()` of long_order_cancel_transaction
        if self.long_order_cancel_transaction:
            _dict['longOrderCancelTransaction'] = self.long_order_cancel_transaction.to_dict()
        # override the default output from pydantic by calling `to_dict()` of short_order_create_transaction
        if self.short_order_create_transaction:
            _dict['shortOrderCreateTransaction'] = self.short_order_create_transaction.to_dict()
        # override the default output from pydantic by calling `to_dict()` of short_order_fill_transaction
        if self.short_order_fill_transaction:
            _dict['shortOrderFillTransaction'] = self.short_order_fill_transaction.to_dict()
        # override the default output from pydantic by calling `to_dict()` of short_order_cancel_transaction
        if self.short_order_cancel_transaction:
            _dict['shortOrderCancelTransaction'] = self.short_order_cancel_transaction.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ClosePosition200Response:
        """Create an instance of ClosePosition200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ClosePosition200Response.parse_obj(obj)

        _obj = ClosePosition200Response.parse_obj({
            "long_order_create_transaction": MarketOrderTransaction.from_dict(obj.get("longOrderCreateTransaction")) if obj.get("longOrderCreateTransaction") is not None else None,
            "long_order_fill_transaction": OrderFillTransaction.from_dict(obj.get("longOrderFillTransaction")) if obj.get("longOrderFillTransaction") is not None else None,
            "long_order_cancel_transaction": OrderCancelTransaction.from_dict(obj.get("longOrderCancelTransaction")) if obj.get("longOrderCancelTransaction") is not None else None,
            "short_order_create_transaction": MarketOrderTransaction.from_dict(obj.get("shortOrderCreateTransaction")) if obj.get("shortOrderCreateTransaction") is not None else None,
            "short_order_fill_transaction": OrderFillTransaction.from_dict(obj.get("shortOrderFillTransaction")) if obj.get("shortOrderFillTransaction") is not None else None,
            "short_order_cancel_transaction": OrderCancelTransaction.from_dict(obj.get("shortOrderCancelTransaction")) if obj.get("shortOrderCancelTransaction") is not None else None,
            "related_transaction_ids": obj.get("relatedTransactionIDs"),
            "last_transaction_id": obj.get("lastTransactionID")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


