# coding: utf-8

"""
    OANDA v20 REST API

    The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.

    The version of the OpenAPI document: 3.0.25
    Contact: api@oanda.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class FundingReason(str, Enum):
    """
    The reason that an Account is being funded.
    """

    """
    allowed enum values
    """
    CLIENT_FUNDING = 'CLIENT_FUNDING'
    ACCOUNT_TRANSFER = 'ACCOUNT_TRANSFER'
    DIVISION_MIGRATION = 'DIVISION_MIGRATION'
    SITE_MIGRATION = 'SITE_MIGRATION'
    ADJUSTMENT = 'ADJUSTMENT'

    @classmethod
    def from_json(cls, json_str: str) -> FundingReason:
        """Create an instance of FundingReason from a JSON string"""
        return FundingReason(json.loads(json_str))


