# coding: utf-8

"""
    OANDA v20 REST API

    The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.

    The version of the OpenAPI document: 3.0.25
    Contact: api@oanda.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class GuaranteedStopLossOrderMode(str, Enum):
    """
    The overall behaviour of the Account regarding guaranteed Stop Loss Orders.
    """

    """
    allowed enum values
    """
    DISABLED = 'DISABLED'
    ALLOWED = 'ALLOWED'
    REQUIRED = 'REQUIRED'

    @classmethod
    def from_json(cls, json_str: str) -> GuaranteedStopLossOrderMode:
        """Create an instance of GuaranteedStopLossOrderMode from a JSON string"""
        return GuaranteedStopLossOrderMode(json.loads(json_str))


