# coding: utf-8

"""
    OANDA v20 REST API

    The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.

    The version of the OpenAPI document: 3.0.25
    Contact: api@oanda.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, Optional
from pydantic import BaseModel, Field, StrictStr

class HomeConversions(BaseModel):
    """
    HomeConversions represents the factors to use to convert quantities of a given currency into the Account's home currency. The conversion factor depends on the scenario the conversion is required for.
    """
    currency: Optional[StrictStr] = Field(None, description="The currency to be converted into the home currency.")
    account_gain: Optional[StrictStr] = Field(None, alias="accountGain", description="The factor used to convert any gains for an Account in the specified currency into the Account's home currency. This would include positive realized P/L and positive financing amounts. Conversion is performed by multiplying the positive P/L by the conversion factor.")
    account_loss: Optional[StrictStr] = Field(None, alias="accountLoss", description="The string representation of a decimal number.")
    position_value: Optional[StrictStr] = Field(None, alias="positionValue", description="The factor used to convert a Position or Trade Value in the specified currency into the Account's home currency. Conversion is performed by multiplying the Position or Trade Value by the conversion factor.")
    additional_properties: Dict[str, Any] = {}
    __properties = ["currency", "accountGain", "accountLoss", "positionValue"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> HomeConversions:
        """Create an instance of HomeConversions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "additional_properties"
                          },
                          exclude_none=True)
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> HomeConversions:
        """Create an instance of HomeConversions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return HomeConversions.parse_obj(obj)

        _obj = HomeConversions.parse_obj({
            "currency": obj.get("currency"),
            "account_gain": obj.get("accountGain"),
            "account_loss": obj.get("accountLoss"),
            "position_value": obj.get("positionValue")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


