# coding: utf-8

"""
    OANDA v20 REST API

    The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.

    The version of the OpenAPI document: 3.0.25
    Contact: api@oanda.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class InstrumentType(str, Enum):
    """
    The type of an Instrument.
    """

    """
    allowed enum values
    """
    CURRENCY = 'CURRENCY'
    CFD = 'CFD'
    METAL = 'METAL'

    @classmethod
    def from_json(cls, json_str: str) -> InstrumentType:
        """Create an instance of InstrumentType from a JSON string"""
        return InstrumentType(json.loads(json_str))


