# coding: utf-8

"""
    OANDA v20 REST API

    The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.

    The version of the OpenAPI document: 3.0.25
    Contact: api@oanda.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class OrderFillReason(str, Enum):
    """
    The reason that an Order was filled
    """

    """
    allowed enum values
    """
    LIMIT_ORDER = 'LIMIT_ORDER'
    STOP_ORDER = 'STOP_ORDER'
    MARKET_IF_TOUCHED_ORDER = 'MARKET_IF_TOUCHED_ORDER'
    TAKE_PROFIT_ORDER = 'TAKE_PROFIT_ORDER'
    STOP_LOSS_ORDER = 'STOP_LOSS_ORDER'
    TRAILING_STOP_LOSS_ORDER = 'TRAILING_STOP_LOSS_ORDER'
    MARKET_ORDER = 'MARKET_ORDER'
    MARKET_ORDER_TRADE_CLOSE = 'MARKET_ORDER_TRADE_CLOSE'
    MARKET_ORDER_POSITION_CLOSEOUT = 'MARKET_ORDER_POSITION_CLOSEOUT'
    MARKET_ORDER_MARGIN_CLOSEOUT = 'MARKET_ORDER_MARGIN_CLOSEOUT'
    MARKET_ORDER_DELAYED_TRADE_CLOSE = 'MARKET_ORDER_DELAYED_TRADE_CLOSE'

    @classmethod
    def from_json(cls, json_str: str) -> OrderFillReason:
        """Create an instance of OrderFillReason from a JSON string"""
        return OrderFillReason(json.loads(json_str))


