# coding: utf-8

"""
    OANDA v20 REST API

    The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.

    The version of the OpenAPI document: 3.0.25

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, Optional
from pydantic import BaseModel, Field
from pyfx.dispatch.oanda.models.stop_loss_details import StopLossDetails
from pyfx.dispatch.oanda.models.take_profit_details import TakeProfitDetails
from pyfx.dispatch.oanda.models.trailing_stop_loss_details import TrailingStopLossDetails

class SetTradeDependentOrdersRequest(BaseModel):
    """
    SetTradeDependentOrdersRequest
    """
    take_profit: Optional[TakeProfitDetails] = Field(None, alias="takeProfit")
    stop_loss: Optional[StopLossDetails] = Field(None, alias="stopLoss")
    trailing_stop_loss: Optional[TrailingStopLossDetails] = Field(None, alias="trailingStopLoss")
    additional_properties: Dict[str, Any] = {}
    __properties = ["takeProfit", "stopLoss", "trailingStopLoss"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> SetTradeDependentOrdersRequest:
        """Create an instance of SetTradeDependentOrdersRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "additional_properties"
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of take_profit
        if self.take_profit:
            _dict['takeProfit'] = self.take_profit.to_dict()
        # override the default output from pydantic by calling `to_dict()` of stop_loss
        if self.stop_loss:
            _dict['stopLoss'] = self.stop_loss.to_dict()
        # override the default output from pydantic by calling `to_dict()` of trailing_stop_loss
        if self.trailing_stop_loss:
            _dict['trailingStopLoss'] = self.trailing_stop_loss.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> SetTradeDependentOrdersRequest:
        """Create an instance of SetTradeDependentOrdersRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return SetTradeDependentOrdersRequest.parse_obj(obj)

        _obj = SetTradeDependentOrdersRequest.parse_obj({
            "take_profit": TakeProfitDetails.from_dict(obj.get("takeProfit")) if obj.get("takeProfit") is not None else None,
            "stop_loss": StopLossDetails.from_dict(obj.get("stopLoss")) if obj.get("stopLoss") is not None else None,
            "trailing_stop_loss": TrailingStopLossDetails.from_dict(obj.get("trailingStopLoss")) if obj.get("trailingStopLoss") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


