# coding: utf-8

"""
    OANDA v20 REST API

    The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.

    The version of the OpenAPI document: 3.0.25

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class TimeInForce(str, Enum):
    """
    The time-in-force of an Order. TimeInForce describes how long an Order should remain pending before being automatically cancelled by the execution system.
    """

    """
    allowed enum values
    """
    GTC = 'GTC'
    GTD = 'GTD'
    GFD = 'GFD'
    FOK = 'FOK'
    IOC = 'IOC'

    @classmethod
    def from_json(cls, json_str: str) -> TimeInForce:
        """Create an instance of TimeInForce from a JSON string"""
        return TimeInForce(json.loads(json_str))


