# coding: utf-8

"""
    OANDA v20 REST API

    The full OANDA v20 REST API Specification. This specification defines how to interact with v20 Accounts, Trades, Orders, Pricing and more.

    The version of the OpenAPI document: 3.0.25

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class WeeklyAlignment(str, Enum):
    """
    The day of the week to use for candlestick granularities with weekly alignment.
    """

    """
    allowed enum values
    """
    MONDAY = 'Monday'
    TUESDAY = 'Tuesday'
    WEDNESDAY = 'Wednesday'
    THURSDAY = 'Thursday'
    FRIDAY = 'Friday'
    SATURDAY = 'Saturday'
    SUNDAY = 'Sunday'

    @classmethod
    def from_json(cls, json_str: str) -> WeeklyAlignment:
        """Create an instance of WeeklyAlignment from a JSON string"""
        return WeeklyAlignment(json.loads(json_str))


